In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
# Replace the path with the correct path for your data.
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

# Note the warning about dtypes.

C:\Users\clyde\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
y2015.shape

(421097, 111)

In [4]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421097
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3

In [20]:
# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [21]:
y2015.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
421090,36371250,39102635.0,10000.0,10000.0,10000.0,36 months,11.99,332.10,B,8 years,...,0.0,1.0,100.0,100.0,0.0,0.0,32950.0,25274.0,9200.0,15850.0
421091,36441262,39152692.0,24000.0,24000.0,24000.0,36 months,11.99,797.03,B,10+ years,...,0.0,2.0,56.5,100.0,0.0,0.0,152650.0,8621.0,9000.0,0.0
421092,36271333,38982739.0,13000.0,13000.0,13000.0,60 months,15.99,316.07,D,5 years,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,36490806,39222577.0,12000.0,12000.0,12000.0,60 months,19.99,317.86,E,1 year,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421094,36271262,38982659.0,20000.0,20000.0,20000.0,36 months,11.99,664.20,B,10+ years,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0

In [22]:
y2015 = y2015[:-2]

In [23]:
pd.get_dummies(y2015)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,...,last_credit_pull_d_Nov-2016,last_credit_pull_d_Oct-2015,last_credit_pull_d_Oct-2016,last_credit_pull_d_Sep-2015,last_credit_pull_d_Sep-2016,application_type_INDIVIDUAL,application_type_JOINT,verification_status_joint_Not Verified,verification_status_joint_Source Verified,verification_status_joint_Verified
0,68009401,72868139.0,16000.0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,...,0,0,0,0,0,1,0,0,0,0
1,68354783,73244544.0,9600.0,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,...,0,0,0,0,0,1,0,0,0,0
2,68466916,73356753.0,25000.0,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,...,0,0,0,0,0,1,0,0,0,0
3,68466961,73356799.0,28000.0,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,...,0,0,0,0,0,1,0,0,0,0
4,68495092,73384866.0,8650.0,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,...,0,0,0,0,0,1,0,0,0,0
5,68506798,73396623.0,23000.0,23000.0,23000.0,8.49,471.77,64000.0,18.28,0.0,...,0,0,0,0,0,1,0,0,0,0
6,68566886,73456723.0,29900.0,29900.0,29900.0,12.88,678.49,65000.0,21.77,0.0,...,0,0,0,0,0,1,0,0,0,0
7,68577849,73467703.0,18000.0,18000.0,18000.0,11.99,400.31,112000.0,8.68,0.0,...,0,0,0,0,0,1,0,0,0,0
8,66310712,71035433.0,35000.0,35000.0,35000.0,14.85,829.90,110000.0,17.06,0.0,...,0,0,0,0,0,1,0,0,0,0
9,68476807,73366655.0,10400.0,10400.0,10400.0,22.45,289.91,104433.0,25.37,1.0,...,0,0,0,0,0,1,0,0,0,0
10,68341763,72928789.0,20000.0,20000.0,20000.0,10.78,432.66,63000.0,10.78,0.0,...,0,0,0,0,0,0,1,1,0,0
11,68356421,73246236.0,22400.0,22400.0,22400.0,12.88,508.30,95000.0,22.98,0.0,...,0,0,0,0,0,1,0,0,0,0
12,68426545,73316365.0,16000.0,16000.0,16000.0,12.88,363.07,70000.0,26.40,0.0,...,0,0,0,0,0,1,0,0,0,0
13,68407277,73297111.0,3600.0,3600.0,3600.0,13.99,123.03,55000.0,5.91,0.0,...,0,0,0,0,0,1,0,0,0,0
14,68355089,73244858.0,24700.0,24700.0,24700.0,11.99,820.28,65000.0,16.06,1.0,...,0,0,0,0,0,1,0,0,0,0
15,68466926,73356763.0,10000.0,10000.0,10000.0,6.49,306.45,85000.0,13.07,0.0,...,0,0,0,0,0,1,0,0,0,0
16,68338832,73542831.0,1400.0,1400.0,1400.0,12.88,47.10,64000.0,34.95,0.0,...,0,0,0,0,0,1,0,0,0,0
17,68426831,73316657.0,11950.0,11950.0,11950.0,13.44,405.18,34000.0,10.20,0.0,...,0,0,0,0,0,1,0,0,0,0
18,66624733,71350547.0,18000.0,18000.0,18000.0,19.48,471.70,150000.0,9.39,0.0,...,0,0,0,0,0,1,0,0,0,0
19,68616873,73519699.0,8000.0,8000.0,8000.0,11.48,263.74,42000.0,34.80,0.0,...,0,0,0,0,0,1,0,0,0,0
20,67275481,72077199.0,20000.0,20000.0,20000.0,8.49,631.26,85000.0,17.61,1.0,...,0,0,0,0,0,1,0,0,0,0
21,68476668,73366513.0,20000.0,20000.0,20000.0,9.17,637.58,180000.0,14.67,0.0,...,1,0,0,0,0,1,0,0,0,0
22,68476702,73366548.0,28000.0,28000.0,28000.0,13.44,949.38,125000.0,7.49,0.0,...,0,0,0,0,0,1,0,0,0,0
23,68436666,73326493.0,5000.0,5000.0,5000.0,13.44,169.54,79000.0,12.70,0.0,...,0,0,0,0,0,1,0,0,0,0
24,68596180,73485987.0,20000.0,20000.0,20000.0,5.32,602.30,65000.0,18.83,0.0,...,0,0,0,0,0,1,0,0,0,0
25,67849662,72708407.0,4225.0,4225.0,4225.0,14.85,146.16,35000.0,15.22,2.0,...,0,0,0,0,0,1,0,0,0,0
26,68526883,73416719.0,15000.0,15000.0,15000.0,5.32,451.73,44000.0,15.34,0.0,...,0,0,0,0,0,1,0,0,0,0
27,68607141,73509983.0,17600.0,17600.0,17600.0,5.32,530.03,88000.0,26.59,0.0,...,1,0,0,0,0,1,0,0,0,0
28,68476715,73366561.0,6000.0,6000.0,6000.0,7.49,186.61,100000.0,13.28,1.0,...,0,0,0,0,0,1,0,0,0,0
29,67715283,72569997.0,16000.0,16000.0,16000.0,12.88,538.18,65000.0,18.96,0.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421063,37041208,39803931.0,17000.0,17000.0,17000.0,15.99,413.32,63078.0,31.70,0.0,...,0,0,0,0,0,1,0,0,0,0
421064,36500819,39232937.0,10300.0,10300.0,10300.0,13.66,237.86,93600.0,15.72,1.0,...,0,0,0,0,0,1,0,0,0,0
421065,36631385,39374138.0,13000.0,13000.0,13000.0,8.19,408.52,85000.0,8.05,1.0,...,0,0,0,0,0,1,0,0,0,0
421066,36231083,38942474.0,15000.0,15000.0,15000.0,11.99,498.15,70000.0,8.47,0.0,...,0,0,0,0,0,1,0,0,0,0
421067,36691397,39434133.0,20000.0,20000.0,20000.0,6.99,617.46,72000.0,27.24,0.0,...,0,0,0,0,0,1,0,0,0,0
421068,36743377,39486112.0,4200.0,4200.0,4200.0,15.99,147.64,48000.0,36.93,0.0,...,0,0,0,0,0,1,0,0,0,0
421069,36331554,39042967.0,26950.0,26950.0,26950.0,8.19,846.88,54000.0,18.11,0.0,...,0,0,0,0,0,1,0,0,0,0
421070,36460697,39182359.0,23000.0,23000.0,23000.0,15.59,554.32,50000.0,31.95,0.0,...,0,0,0,0,0,1,0,0,0,0
421071,35773415,38468842.0,18700.0,18700.0,18700.0,17.86,473.44,52000.0,11.28,0.0,...,0,0,0,0,0,1,0,0,0,0
421072,36250801,38962184.0,6000.0,6000.0,6000.0,17.86,216.50,90000.0,2.84,0.0,...,0,0,0,0,0,1,0,0,0,0
421073,36371802,39103231.0,15000.0,15000.0,15000.0,11.44,329.44,57000.0,15.77,0.0,...,0,0,0,0,0,1,0,0,0,0
421074,36440728,39152101.0,25000.0,25000.0,25000.0,15.99,607.82,103000.0,5.27,0.0,...,0,0,0,0,0,1,0,0,0,0
421075,36361815,39093260.0,26500.0,26500.0,26500.0,8.67,545.87,92000.0,29.60,1.0,...,0,0,0,0,0,1,0,0,0,0
421076,35591131,38288343.0,25000.0,25000.0,25000.0,15.59,602.52,55000.0,5.52,0.0,...,0,0,0,0,0,1,0,0,0,0
421077,36201871,38913321.0,21000.0,21000.0,21000.0,6.03,639.15,65000.0,17.09,0.0,...,0,0,0,0,0,1,0,0,0,0
421078,36381756,39013193.0,8000.0,8000.0,8000.0,8.19,251.40,50000.0,17.62,0.0,...,0,0,0,0,0,1,0,0,0,0
421079,36231724,38943173.0,12000.0,12000.0,12000.0,9.49,384.34,40000.0,25.65,1.0,...,0,0,1,0,0,1,0,0,0,0
421080,36301729,39023153.0,10000.0,10000.0,10000.0,6.49,306.45,75000.0,33.66,0.0,...,0,0,0,0,0,1,0,0,0,0
421081,36250208,38961532.0,13150.0,13150.0,13150.0,14.99,312.77,30000.0,1.00,0.0,...,0,0,0,0,0,1,0,0,0,0
421082,36241316,38952731.0,6225.0,6225.0,6225.0,16.49,220.37,27000.0,18.58,0.0,...,0,0,0,0,0,1,0,0,0,0
421083,36231718,38943165.0,10775.0,10775.0,10775.0,6.03,327.95,54000.0,13.22,1.0,...,0,0,0,0,0,1,0,0,0,0
421084,36381704,39013139.0,7000.0,7000.0,7000.0,14.31,240.30,57000.0,16.80,2.0,...,0,0,0,0,0,1,0,0,0,0
421085,36421485,39142898.0,4000.0,4000.0,4000.0,8.67,126.59,50000.0,12.63,0.0,...,0,0,1,0,0,1,0,0,0,0
421086,35094480,37777829.0,7500.0,7500.0,7500.0,9.49,240.22,40000.0,25.63,0.0,...,0,0,0,0,0,1,0,0,0,0
421087,36260758,38972123.0,10850.0,10850.0,10850.0,19.24,399.04,32000.0,29.44,0.0,...,0,0,1,0,0,1,0,0,0,0
421088,36221446,38932858.0,11575.0,11575.0,11575.0,15.59,404.61,25400.0,27.08,0.0,...,1,0,0,0,0,1,0,0,0,0
421089,36330911,39042282.0,12000.0,12000.0,12000.0,11.99,398.52,63000.0,23.69,1.0,...,0,0,0,0,0,1,0,0,0,0
421090,36371250,39102635.0,10000.0,10000.0,10000.0,11.99,332.10,31000.0,28.69,0.0,...,0,0,0,0,0,1,0,0,0,0
421091,36441262,39152692.0,24000.0,24000.0,24000.0,11.99,797.03,79000.0,3.90,0.0,...,0,0,0,0,0,1,0,0,0,0
421092,36271333,38982739.0,13000.0,13000.0,13000.0,15.99,316.07,35000.0,30.90,0.0,...,0,0,0,0,0,1,0,0,0,0

In [24]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)
import time
start_time = time.time()
cross_val_score(rfc, X, Y, cv=10)
print("--- %s seconds ---" % (time.time() - start_time))
# This is the model we'll be using.

C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

--- 541.0818839073181 seconds ---

In [26]:
X.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,...,last_credit_pull_d_Nov-2016,last_credit_pull_d_Oct-2015,last_credit_pull_d_Oct-2016,last_credit_pull_d_Sep-2015,last_credit_pull_d_Sep-2016,application_type_INDIVIDUAL,application_type_JOINT,verification_status_joint_Not Verified,verification_status_joint_Source Verified,verification_status_joint_Verified
0,68009401,72868139.0,16000.0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,...,0,0,0,0,0,1,0,0,0,0
1,68354783,73244544.0,9600.0,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,...,0,0,0,0,0,1,0,0,0,0
2,68466916,73356753.0,25000.0,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,...,0,0,0,0,0,1,0,0,0,0
3,68466961,73356799.0,28000.0,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,...,0,0,0,0,0,1,0,0,0,0
4,68495092,73384866.0,8650.0,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,...,0,0,0,0,0,1,0,0,0,0

In [36]:
# This is the model we'll be using.
from sklearn import tree

# A convenience for displaying visualizations.
from IPython.display import Image

# Packages for rendering our tree.
import pydotplus
import graphviz
# Initialize and train our tree.
decision_tree = tree.DecisionTreeClassifier(
    criterion='entropy',
    max_features=1,
    max_depth=4,
)

start_time = time.time()
cross_val_score(decision_tree, X, Y, cv=10)
print("--- %s seconds ---" % (time.time() - start_time))

--- 41.13182330131531 seconds ---

In [37]:
cross_val_score(decision_tree, X, Y, cv=10)

array([0.82083066, 0.68616276, 0.68279072, 0.68862503, 0.69002612,
       0.68703396, 0.77399131, 0.68680536, 0.69921866, 0.6885717 ])

In [38]:
cross_val_score(rfc, X, Y, cv=10)

C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\clyde\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.97929282, 0.98033768, 0.9816675 , 0.98176205, 0.97022085,
       0.97782   , 0.95753877, 0.9806925 , 0.98024082, 0.98059659])